### ISSUE TITLE
How can I don't show datapoint in null values?

### ISSUE THREAD

**Issue by hnrqsss** [N1ghtly/react-native-responsive-linechart#10]
For exemple.
yValues = [ 10, 20, 30, 40, null, 50 ]
xValues= [ 1, 2, 3, 4, 5, 6 ]
Actually if I use values like this the null value is marked with a dataPoint, but I can't show it.

I'd like to show a chart like this: 

![https://firebasestorage.googleapis.com/v0/b/mercadodev-846c7.appspot.com/o/IMG_20190701_095936.jpg?alt=media&token=7ec78bbf-a3be-49be-a27c-4f76d6c864c6](https://firebasestorage.googleapis.com/v0/b/mercadodev-846c7.appspot.com/o/IMG_20190701_095936.jpg?alt=media&token=7ec78bbf-a3be-49be-a27c-4f76d6c864c6)

 Is this possible ?

**Comment by N1ghtly** [comment]
This is not possible in the current release.

**Comment by DhavalKakadiya** [comment]
I also want to know a solution to that type of data. I am using a react-native-svg chart. If anyone have solution for it then please share it.

**Comment by N1ghtly** [comment]
Hi @hnrqsss and @DhavalKakadiya  , I'm closing this issue because version 3.0.0 is out. This functionality is supported in the new version!
