### ISSUE TITLE
Show different colors on a single line in line chart

### ISSUE THREAD

**Issue by gayathri-nair03** [N1ghtly/react-native-responsive-linechart#108]
I need to show 2 different colors in a line. Is that possible here now?

**Comment by gjakobson** [comment]
I got it done very simply:  literally display 2 lines, each in a different color, the 2nd line starting where the 1st line ends.

So for example, if your data is D = [{1,1},{2,1},{3,2},{4,0}] and you want 2 different colors starting in the middle of the series, split it into D1=[{1,1},{2,1}] and D2=[{3,2},{4,0}]

and now very literally do
<Chart>
  <Line data=D1 color.....>
  <Line data=D2 color...>

Works perfectly for me.
