### ISSUE TITLE
RNSVGText, can't able to create SVG image, 

### ISSUE THREAD

**Issue by Anu-kumari** [N1ghtly/react-native-responsive-linechart#12]
We check our input for data and labels but not able to find this error,
Please help me to resolve ASAP
` Invariant Violation: Invariant Violation: [1089,"RNSVGText",11,{"matrix":[1,0,0,1,0,0],"rotation":0,"scaleX":1,"scaleY":1,"x":["<<NaN>>"],"y":[160],"propList":["fill"],"opacity":1,"fill":[0,-8947849],"fillRule":1,"fillOpacity":1,"stroke":null,"strokeOpacity":1,"strokeLinecap":0,"strokeLinejoin":0,"strokeDasharray":null,"strokeWidth":1,"strokeDashoffset":null,"strokeMiterlimit":4,"vectorEffect":0,"font":{"fontWeight":"400","fontSize":12,"textAnchor":"middle"},"dx":[],"dy":[12],"rotate":[]}] is not usable as a native method argument
- node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:253:8 in enqueueNativeCall
- node_modules\react-native\Libraries\BatchedBridge\NativeModules.js:137:8 in fn
`

**Comment by N1ghtly** [comment]
Hi @Anu-kumari  , I'm closing this issue because version 3.0.0 is out. If this issue still occurs with the new version, please open a new issue. I'm committing myself to monitor & develop this library more consistently.
