### ISSUE TITLE
How can I create a new line within the tooltip?

### ISSUE THREAD

**Issue by apfz** [N1ghtly/react-native-responsive-linechart#133]
I have tried to add \n and \r to the formatter output but I am unable to create a new line. 

`formatter: (v: ChartDataPoint) =>  'Testing a very long \n\r sentence'`

How do I accomplish this?

**Comment by apfz** [comment]
I have created a custom tooltip to do this.

**Comment by IKTANIM** [comment]
Can you please share the custom tooltips code.

**Comment by KartavyaParekh** [comment]
How you mange this thing for the tooltips

**Comment by rnidea2code** [comment]
How you manage this things
