### ISSUE TITLE
If interpolation is spline, Tooltip not working like expected. Also If there are so much data points, it is the same.

### ISSUE THREAD

**Issue by RNTop** [N1ghtly/react-native-responsive-linechart#18]

**Comment by sraza295** [comment]
@RNTop Did you find any solution?

**Comment by N1ghtly** [comment]
Hi guys, I'm closing this issue because version 3.0.0 is out. Interpolation is currently no longer supported, but if there is demand I will implement it again. I'm committing myself to monitor & develop this library more consistently.

**Comment by N1ghtly** [comment]
@sraza295 @RNTop Spline interpolation is now implemented in v3. Tooltips should behave correctly as well!
