### ISSUE TITLE
Questions: supporting RTL languages? axis labels formatting

### ISSUE THREAD

**Issue by SaeedZhiany** [N1ghtly/react-native-responsive-linechart#27]
Hi,
Thanks for your effort on this module.

I have two questions before start using it.

1. Does it support RTL languages (like Persian(Farsi) or Arabic) for axis labels and tooltips?
2. Is there functionality that I can format the Y and X axis labels using my own logic? (for example, convert the Y-values to MegaByte or Centigrade and etc.  or even converting x-axis date labels to another calendar system like Jalali (Shamsi) Calendar?

**Comment by N1ghtly** [comment]
Hi @SaeedZhiany!

1. I'm not sure to be honest. If react-native-svg supports it through its `<Text />` component, it's definitely doable. How do you use RTL in other places in RN?
2. Absolutely. The Axis components can be given a `formatter` in the theme prop. Check out the vertical axis in this example: https://react-native-responsive-linechart.surge.sh/docs/line#combined-with-area-

**Comment by SaeedZhiany** [comment]
Thanks

> I'm not sure to be honest. If react-native-svg supports it through its <Text /> component, it's definitely doable. How do you use RTL in other places in RN?

AFAIK `<Text/>` of react-native-svg does not support it. but `<TSpan>` does. [it recently added](https://github.com/react-native-community/react-native-svg/issues/439#issuecomment-524983074). its developer, @msand, may have new information about it.

**Comment by N1ghtly** [comment]
I will have a look at it!

**Comment by N1ghtly** [comment]
I tried with the text example from the issue you mentioned, and I see no issues:

![Screenshot 2020-08-29 at 14 58 11](https://user-images.githubusercontent.com/1395284/91637358-26cf9e00-ea08-11ea-9d15-9e279e7d2c8c.png)

Does this look okay to you or am I missing something here? (maybe it should actually be reversed?)

**Comment by SaeedZhiany** [comment]
It looks right. thanks.

> (maybe it should actually be reversed?)

no, it is exactly what it should be 👍

**Comment by SaeedZhiany** [comment]
Just one more question, are you using `<Text>` component for labels and tooltip? or `<Tspan>`?

**Comment by N1ghtly** [comment]
Great! Closing this.

**Comment by SaeedZhiany** [comment]
Hi again, @xanderdeseyn 

do you remember what version of react-native-svg you used when testing Persian/Arabic text rendering in [this comment](https://github.com/N1ghtly/react-native-responsive-linechart/issues/27#issuecomment-683287120)?


I just start using your library and upgraded my react-native-svg in my project to v12.1.1 and the texts are cluttered. 😕 It seems @msand has reverted the changes about the workaround for RTL languages. but I can't remember the last version that was working properly.

![Screenshot_1621755037](https://user-images.githubusercontent.com/13766432/119252066-57232200-bbbf-11eb-831f-8e7f87b566a0.png)

**Comment by Farzin-Firoozi** [comment]
> Hi again, @N1ghtly
> 
> do you remember what version of react-native-svg you used when testing Persian/Arabic text rendering in [this comment](https://github.com/N1ghtly/react-native-responsive-linechart/issues/27#issuecomment-683287120)?
> 
> I just start using your library and upgraded my react-native-svg in my project to v12.1.1 and the texts are cluttered. 😕 It seems @msand has reverted the changes about the workaround for RTL languages. but I can't remember the last version that was working properly.
> 
> ![Screenshot_1621755037](https://user-images.githubusercontent.com/13766432/119252066-57232200-bbbf-11eb-831f-8e7f87b566a0.png)

same issue here
![Screenshot_1631427942](https://user-images.githubusercontent.com/52259209/132974516-db23846a-48d3-49b0-bd3f-3f504bf650ba.png)

**Comment by SaeedZhiany** [comment]
@xanderdeseyn 

It seems only y-Axis using `TSpan` element and the others are all `<Text>` elements, or if you are already using `TSpan` for all texts, you're not set `inlineSize` prop for them. (inlineSize are an important value (workaround) to make `TSpan`s work for RTL languages.

you can take a look at [this comment](https://github.com/react-native-svg/react-native-svg/issues/439#issuecomment-524983074) from @msand.

**Comment by amiinous** [comment]
use this repo https://github.com/font-store/persian-reshaper to prepare RTL text to be used in SVG Text component

**Comment by Farzin-Firoozi** [comment]
@amiinous Tnx You're a saviour!

**Comment by SaeedZhiany** [comment]
@Farzin-Firoozi did the persian-reshaper package help you? I didn't see any improvement

**Comment by Farzin-Firoozi** [comment]
> @Farzin-Firoozi did the persian-reshaper package help you? I didn't see any improvement

My issue was with [victory-native](https://formidable.com/open-source/victory/docs/native/ ) that uses `react-native-svg` and this converter worked for me.

**Comment by SaeedZhiany** [comment]
Great!

I'm also starting to use victory-native. does persian-reshaper package perfectly work on react-native? if yes which function you're using?

I just figure out that the Persian characters cluttering in react-native-svg is happening on Android only and iOS just works fine out of the box. that's why [@xanderdeseyn's comment](https://github.com/xanderdeseyn/react-native-responsive-linechart/issues/27#issuecomment-683287120) look's ok. I'm pretty sure that he's captured the image from iOS device/emulator

**Comment by SaeedZhiany** [comment]
I found another reshaper package that has better documentation and it's working fine for me.

https://github.com/soimy/arabic-persian-reshaper
