### ISSUE TITLE
Error Area Chart with only one point

### ISSUE THREAD

**Issue by jhonwms** [N1ghtly/react-native-responsive-linechart#34]
i am getting an error when i have only one point for the chart -> 

`Chart data={[
 { x: -2, y: 15 },
]}`

Error -> 
![image00](https://user-images.githubusercontent.com/62893194/95772085-c926a680-0c81-11eb-8f33-dfa790dee324.png)

**Comment by N1ghtly** [comment]
I will have a look at it 👍

**Comment by N1ghtly** [comment]
Fixed in v5.2.1
