### ISSUE TITLE
Feature Request: Support for stock line chart

### ISSUE THREAD

**Issue by SaeedZhiany** [N1ghtly/react-native-responsive-linechart#36]
it would be great if you can add support for stock line charts.

![image](https://user-images.githubusercontent.com/13766432/100059600-9656fd00-2e40-11eb-90c0-b9fcd8f918c3.png)

https://www.highcharts.com/demo/stock/basic-line

**Comment by N1ghtly** [comment]
Looks cool, but I believe you can create this with currently existing functionality. I'm trying not to bloat the library to much, so I probably won't implement this kind of specific chart anytime soon

**Comment by SaeedZhiany** [comment]
I see, maybe you can add this issue to your repository's milestone, RN has a lack of js implementation for this kind of chart and it would be great have it out of the box. otherwise, it can be closed.

However, thanks for your attention and response.

**Comment by N1ghtly** [comment]
I'm going to close it, but I'll keep it in mind :)
