### ISSUE TITLE
onTooltipSelectEnd event does not trigger

### ISSUE THREAD

**Issue by chende008** [N1ghtly/react-native-responsive-linechart#47]
In the latest version 5.4.1, the onTooltipSelectEnd event is not triggered, but it is normal in the 5.4.0 version

**Comment by N1ghtly** [comment]
I'll check it out! Thanks for reporting

**Comment by N1ghtly** [comment]
Should be fixed in v5.4.2! Feel free to re-open if you still encounter issues.
