### ISSUE TITLE
Tooltip does not persist, when dragging instead of tapping

### ISSUE THREAD

**Issue by tlow92** [N1ghtly/react-native-responsive-linechart#48]
Hi,

1. When tapping the Line the tooltip stays open, which is correct.
2. When touching and dragging the line the tooltip moves with the cursor. Upon release the tooltip is removed.

Is it supposed to behave like this? I would expect the tooltip to stay when releasing after the "touch and drag" interaction.

Edit: Using version 5.4.1

**Comment by N1ghtly** [comment]
I suppose it should be configurable. I'll have a look at it!

**Comment by N1ghtly** [comment]
v5.4.2 now exposes a new prop on Line: `hideTooltipOnDragEnd`

Set to true if the tooltip should be hidden when the user stops dragging the chart. It now persists by default.

**Comment by tlow92** [comment]
Thanks, working great!
