### ISSUE TITLE
[Android] Tooltip closes immediately after touching

### ISSUE THREAD

**Issue by tlow92** [N1ghtly/react-native-responsive-linechart#52]
Hi,

on Android there seems to be bug, where the Tooltip is opened for a short period of time after touching but closes immediately. When touching and holding for a second it stays open.

Screen recording of the demo project on my OnePlus 6 is attached below.

https://user-images.githubusercontent.com/12113052/104187126-ae4a0680-5417-11eb-9897-24ff5285e514.mp4

**Comment by N1ghtly** [comment]
I will check it out asap, thanks for reporting

**Comment by N1ghtly** [comment]
Can you confirm that you run into this issue with the last version (v5.4.3)? I can't reproduce it on my side.

**Comment by N1ghtly** [comment]
Should definitely be fixed in v5.5.0! Please close this if you can confirm 👍

**Comment by tlow92** [comment]
It's indeed fixed in latest version! Thanks alot!
