### ISSUE TITLE
The vertical axis label is hidden

### ISSUE THREAD

**Issue by chende008** [N1ghtly/react-native-responsive-linechart#53]
https://user-images.githubusercontent.com/4397067/104445135-b9e22c80-55d3-11eb-9fcb-4ce1d498f17d.mov

During the sliding process, I don’t know why the first and last labels of the vertical axis are hidden (no rule found), I don’t know what I did wrong

**Comment by N1ghtly** [comment]
Wow, that is incredibly weird! I'll see if I can reproduce this

**Comment by chende008** [comment]
Hello, I wrote a demo program, which can reproduce the above problems stably. Please take a look at it. The following is the demo link address [responsive_linechart_bug](https://github.com/chende008/responsive_linechart_bug)

**Comment by N1ghtly** [comment]
Thanks for the demo. I'll check it out asap.

**Comment by chende008** [comment]
Hello, may I ask the question I have feedback, can you reproduce it smoothly through Demo? Is there any new progress in fixing the problem?

**Comment by N1ghtly** [comment]
hi @chende008, I have not been able to look at it yet, but I should have some time today!

**Comment by N1ghtly** [comment]
Hmm your sample app is broken on the latest release (5.5.0). 

`Warning: Maximum update depth exceeded. This can happen when a component calls setState inside useEffect, but useEffect either doesn't have a dependency array, or one of the dependencies changes on every render.
    in ForwardRef(Line) (at App.js:54)`
    
    I'll have to check this out first

**Comment by N1ghtly** [comment]
Issue should be fixed in v5.5.1, as well as the error I encountered above ^.
Turned out to be a floating point comparison going wrong: 0.4404 < 0.44039999999999

Thanks for providing a reproducible demo, would not have found it otherwise.

**Comment by chende008** [comment]
Thank you very much, confirm that the issue has been fixed!
