### ISSUE TITLE
Setting large x values for ViewportOrigin doesn't work

### ISSUE THREAD

**Issue by zameerascentic** [N1ghtly/react-native-responsive-linechart#59]
With a x range set with a state like this` xDomain={{ min: 0, max: xMax }}` which xMax state value comes around 65.
When we set the origin as this where `viewport={{ size: { width: 7 }, initialOrigin: {x: xMax, y: 0}}`, 
doesn't scroll to 65, but like half of it. 
**But if we set 65 directly it works, but with a changing state it doesn't work.**

**Comment by N1ghtly** [comment]
Hmm, you are setting the initialOrigin to the most-right point of the chart though, so that wouldn't work. If you want to scroll immediately to the end, can you try setting initialOrigin to xMax - width (7 in this case)?

**Comment by zameerascentic** [comment]
xMax - 7 => 65 - 7
Comes to the left most - starting point. Doesn't go to the right most point.

**Comment by N1ghtly** [comment]
I'm still not entirely clear to me what your issue is, could you provide a screenshot maybe?

**Comment by zameerascentic** [comment]
With this setting,
```
 xDomain={{ min: 0, max: xMax }}
        yDomain={{ min: 0, max: 200 }}
        viewport={{
          size: { width: 7 },
          initialOrigin: { x: xMax, y: 0 },
```
(xMax is set to 65 in the state)
This is what I get, **at the first render graph is going to half of the graph.** 
![image](https://user-images.githubusercontent.com/31923811/106635532-f7205580-65a6-11eb-9f5b-4973383c50f0.png)

But given the documentation, this is how it should be? the graph should be scrolling to any X value (in this case far end of the right corner - to X= 65). Check the dates on X axis.
![image](https://user-images.githubusercontent.com/31923811/106635557-fe476380-65a6-11eb-8614-eaa4abb31fdc.png)

Your suggestion 
> setting initialOrigin to xMax - width (7 in this case)

Did not work, because xMax is 65 and width is 7, so,
```
 xDomain={{ min: 0, max: xMax }}
        yDomain={{ min: 0, max: 200 }}
        viewport={{
          size: { width: 7 },
          initialOrigin: { x: xMax-7, y: 0 }, // x will be 65 - 7
```

**Comment by N1ghtly** [comment]
Just so we're on the same page; in the following situation:
```
xDomain={{ min: 0, max: 50 }}
yDomain={{ min: 0, max: 200 }}
viewport={{
  size: { width: 10 },
  initialOrigin: { x: 40, y: 0 },
}}
```

We would expect the chart to render the part from 40-50 on the x axis.
`viewport.width + initialOrigin.x` can *never* exceed `xDomain.max`

**Comment by zameerascentic** [comment]
Thanks for bearing with me on the issue.
This will work 
`initialOrigin: { x: 40, y: 0 },
`
my issue is that,

this will not work
setxMax(10); //in the useEffects

and 
`initialOrigin: { x: xMax, y: 0 },
`
That's the issue I'm talking, when it's set through the useState hook in useEffects, it doesn't work.
Except that, really great work, library works great and fits for our use case than almost all chart libraries out there.

**Comment by N1ghtly** [comment]
Chart now has a method setViewportOrigin where you can imperatively change it! Please close if this solves your issue :)

**Comment by zameerascentic** [comment]
Solved it! thanks!
