### ISSUE TITLE
how to show tooltip value in x Axis

### ISSUE THREAD

**Issue by hamidashoor98** [N1ghtly/react-native-responsive-linechart#68]
how to show tooltip value in x Axis
tooltip just show Y Axis :
![image](https://user-images.githubusercontent.com/54837510/109639867-f7d7e780-7b64-11eb-96ac-0997d9df6e03.png)
and I want show the X Axis together

**Comment by N1ghtly** [comment]
You will have to use a custom Tooltip component. Check out the implementation of Tooltip.tsx!
