### ISSUE TITLE
Set horizontal axis in be in time (not number)

### ISSUE THREAD

**Issue by benjaminle9x** [N1ghtly/react-native-responsive-linechart#70]
How do I set the horizontal axis to be in time (E.g hh:mm)?

**Comment by jasonwu13** [comment]
i want the same feature

**Comment by BlackWild** [comment]
In your `<HorizontalAxis />` component you can use a label formatter like this:

``` jsx
<HorizontalAxis theme={{
  labels: { formatter: (v) => moment(v).format("H:mm") },
}} />
```

I use `Moment.js` for formatting but you can use anything you want!

**Comment by N1ghtly** [comment]
Like BlackWild explained, use any date lib to format your value to a date :)
