### ISSUE TITLE
Multi-coloured line

### ISSUE THREAD

**Issue by benjaminle9x** [N1ghtly/react-native-responsive-linechart#77]
How do I set different line colours between each point? (E.g. if y value < 12, the line colour is red. else if y value > 12, the line colour is blue)

**Comment by xanderdeseyn** [comment]
Not supported atm.

**Comment by adrian-burkhart** [comment]
@benjaminle9x Probably not relevant for you anymore, but I think this issue can be solved by adding two <Line /> components, as outlined here by @gjakobson: https://github.com/xanderdeseyn/react-native-responsive-linechart/issues/108#issuecomment-890430625
