### ISSUE TITLE
Line chart x-axis labels text is overlapping. 

### ISSUE THREAD

**Issue by MuhammadUsman786786** [N1ghtly/react-native-responsive-linechart#8]
![Capture](https://user-images.githubusercontent.com/29137881/57359894-aeb3d980-712d-11e9-87c0-08acce523f97.PNG)

In this image x-axis of the graph is overlapping. How can I hide the overlapping text so for now?
In the image, 12 May and 13 May are overlaps. I want to hide any of these.

**Comment by N1ghtly** [comment]
Hi, there is no solution for this at the moment. What would be your preferred solution? It's kind of a difficult problem because you can't know the dimensions of text exactly with SVG...

**Comment by MuhammadUsman786786** [comment]
@N1ghtly one solution is that rotation of labels. But this library does provide this option also.

**Comment by N1ghtly** [comment]
Hi @MuhammadUsman786786, I will include rotation config on labels in an upcoming release. Stay tuned!

**Comment by N1ghtly** [comment]
@MuhammadUsman786786 This is now implemented since version 3.1.0.
