### ISSUE TITLE
Chart does not display all data 

### ISSUE THREAD

**Issue by jerus1403** [N1ghtly/react-native-responsive-linechart#81]
My data array has about 28 element but chart does not display all of them for some reason. I used a combination of Line and Area to display my chart. Like you see, in the renderChartLine function, I log [data] to the console and see all 28 elements from my data but when I check the chart, it only displays about 11 elements or so. I include 2 pictures of my code and hope that anyone can see what I'm not seeing. 
<img width="1046" alt="Screen Shot 2021-05-04 at 9 48 32 AM" src="https://user-images.githubusercontent.com/32551853/117022611-fdb18c80-acbd-11eb-8bdc-c00ed386c9da.png">
<img width="1054" alt="Screen Shot 2021-05-04 at 9 43 31 AM" src="https://user-images.githubusercontent.com/32551853/117021880-5cc2d180-acbd-11eb-91f2-d4b235f1ae98.png">
<img width="1047" alt="Screen Shot 2021-05-04 at 9 43 47 AM" src="https://user-images.githubusercontent.com/32551853/117021893-5f252b80-acbd-11eb-805d-08ee8a99efa5.png">

**Comment by xanderdeseyn** [comment]
Hi, probably something wrong with the `viewport` or `yDomain` you are setting. Does it work if you leave out those props?

**Comment by jerus1403** [comment]
Thank you for helping me out. I figured it out. Yes, it was my setting for the yDomain.

**Comment by xanderdeseyn** [comment]
Great!
