### ISSUE TITLE
interpolation spline along with dataPoint was creating problem

### ISSUE THREAD

**Issue by N140233** [N1ghtly/react-native-responsive-linechart#9]

**Comment by N1ghtly** [comment]
Can you elaborate?

**Comment by AilsonFreire** [comment]
![Screenshot_20190916-105429](https://user-images.githubusercontent.com/9551815/64964643-d6e8dd00-d871-11e9-8aa9-5d5c36081a56.png)

**Comment by lucca-cardial** [comment]
Do you solved this ?

**Comment by ArvindKer** [comment]
![Screenshot 2020-03-12 at 9 38 30 PM](https://user-images.githubusercontent.com/45869604/76541579-d7250680-64a9-11ea-839c-7118034cb751.png)
Having same issue when using spline and dataPoint at the same time.

**Comment by N1ghtly** [comment]
Hi guys, I'm closing this issue because version 3.0.0 is out. Interpolation is not supported in v3.0.0 at the moment, but if there is enough demand I will add the feature again. I'm committing myself to monitor & develop this library more consistently.

**Comment by mashad6** [comment]
@ArvindKer have you found any workaround for this? i am facing the same issue
